name: TPASS
description: TPASS
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.5+108
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State manage
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.1.0

  #logic
  http: ^1.1.0
  flutter_secure_storage: ^6.1.0
  shared_preferences: ^2.0.17
  json_annotation: ^4.7.0
  url_launcher: ^6.1.10
  http_parser: ^4.0.2
  go_router: ^8.1.0
  copy_with_extension: ^5.0.3
  convert: ^3.1.1

  #view
  flutter_icon_snackbar: ^1.1.4
  flutter_icon_dialog: ^1.2.1
  icon_animated: ^1.2.1
  flutter_static_utility: ^1.0.2
  responsive_framework: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  cached_network_image: ^3.3.0
  flutter_html: ^3.0.0-beta.1
  auto_size_text: ^3.0.0
  fl_chart: ^0.69.2
  dotted_border: ^2.0.0+3
  blurrycontainer: ^1.0.2
  lottie: ^2.6.0
  flutter_spinkit: ^5.2.0
  simple_ripple_animation: ^0.0.7


  #util
  url_strategy: ^0.2.0
  logger: ^1.1.0
  intl: ^0.19.0
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  permission_handler: ^8.3.0
  envied: ^0.3.0+3
  encrypt: ^5.0.1
  nfc_manager: ^3.3.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  file_picker: ^5.3.3
  geolocator: ^10.0.0
  flutter_blue_plus: ^1.32.11
  android_intent_plus: ^4.0.3
  qr_code_scanner: ^1.0.1
  uni_links: ^0.5.1
  version: ^3.0.2
  syncfusion_flutter_xlsio: ^24.1.41
  #firebase
  firebase_core: ^2.8.0
  firebase_performance: ^0.9.0+16
  firebase_crashlytics: ^3.0.17
  firebase_analytics: ^10.1.6
  firebase_installations: ^16.3.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  source_gen: ^1.3.2
  build_runner: ^2.4.4
  json_serializable: ^6.5.4
  envied_generator: ^0.3.0+3
  copy_with_extension_gen: ^5.0.3
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Thin.otf
          weight: 100
        - asset: assets/fonts/SUIT-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/SUIT-Light.otf
          weight: 300
        - asset: assets/fonts/SUIT-Regular.otf
          weight: 400
        - asset: assets/fonts/SUIT-Medium.otf
          weight: 500
        - asset: assets/fonts/SUIT-Bold.otf
          weight: 700
        - asset: assets/fonts/SUIT-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/SUIT-Heavy.otf
          weight: 900


